package com.boclips.events.types;

import lombok.*;

import java.util.Locale;

@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class Captions {

    @NonNull
    private CaptionsFormat format;

    @NonNull
    private Boolean autoGenerated;

    @NonNull
    private Locale language;

    @NonNull
    private String content;
}
