package com.boclips.events.types;

import lombok.*;

@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class Captions {

    @NonNull
    private CaptionsFormat format;

    @NonNull
    private boolean autoGenerated;

    @NonNull
    private String language;

    @NonNull
    private String content;
}
